name: my gen AI proj

on:
  schedule:
    - cron: "0 10 * * *" # Runs every day at 10:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Specify your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements file

      - name: Run the model
        run: |
          python loadModel.py  # Adjust if you need to pass any arguments
